apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: helloworld-tls-cert-user15
 namespace: namespace15
spec:
 # name of the tls secret to store
 # the generated certificate/key pair
 secretName: helloworld-tls-certs-user15
 isCA: true
 issuerRef:
   # issuer created in step 1
   name: self-ca-issuer-user15
   kind: Issuer
 commonName: helloworlduser9.172.16.70.58.nip.io
 dnsNames:
 # one or more fully-qualified domain name
 # can be defined here
 - helloworlduser9.172.16.70.58.nip.io
