apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: hello-cert-tls
 namespace: <namespace>
spec:
 # name of the tls secret to store
 # the generated certificate/key pair
 secretName: hello-deployment-tls-ca-key-pair
 isCA: true
 issuerRef:
   # issuer created in step 1
   name: hello-myself-tls
   kind: Issuer
 commonName: "foo.bar"
 dnsNames:
 # one or more fully-qualified domain name
 # can be defined here
 - foo.bar
