apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: hello-user15-cert-tls
 namespace: namespace15
spec:
 # name of the tls secret to store
 # the generated certificate/key pair
 secretName: hello-user15-tls-ca-key-pair
 isCA: true
 issuerRef:
   # issuer created in step 1
   name: hello-user15-tls
   kind: Issuer
 commonName: "foouser15.bar"
 dnsNames:
 # one or more fully-qualified domain name
 # can be defined here
 - foouser15.bar
